  name: Enabling Helm Chart Scan and Commit to application config repo

  on:
    workflow_dispatch:
      inputs:
        repo_name:
          description: 'Repository Name'
          required: true
          type: string

        pr_branch:
          description: 'PR Branch Name'
          required: true
          type: string

        release_branch:
          description: 'Release Branch Name'
          required: true
          type: string


  jobs:
    Enable_Helm_Chart_Scan:
      name: Enable Helm Chart Scan 
      runs-on: medium-runner

      steps:

        - name: Create Github App Token
          uses: actions/create-github-app-token@v1
          id: app-token
          with:
            app-id: ${{ vars.APP_ID_GTIHUB }}
            private-key: ${{ secrets.PRIVATE_KEY_GITHUB }}
            owner: m2pfintech
            repositories: ${{ github.event.repository.name }}

        - name: Checkout 
          uses: actions/checkout@v4

        - name: Checkout 
          uses: actions/checkout@v4
          with:
            repository: m2pfintech/${{ inputs.repo_name }}
            path: ${{ inputs.repo_name }}
            token: ${{ steps.app-token.outputs.token }}
            ref: uat

        - name: ls
          run: |
            ls 
            pwd

        - name: commit
          run: |
          working-directory: ${{ inputs.repo_name }}
            ls -l
            git fetch origin ${ input.release_branch }
            git checkout -b ${{ input.pr_branch}}  origin/${ input.release_branch }
            ls -l
            git branch
            echo '' >> .github/workflows/ci.yaml
            cat ${GITHUB_WORKSPACE}/Helm-Chart >> .github/workflows/ci.yaml
            git config --global user.name "DevSecOps"
            git config --global user.email "devsecops@gmail.com"
            git add .
            git commit -m "Helm Chart Scan"
            git push --set-upstream origin ${{ input.pr_branch }}

        - name: Create pull request
          run: |
            curl -X POST \
            -H "Authorization: Bearer ${{ steps.app-token.outputs.token }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/m2pfintech/poc-m2p-devsecops-application-config/pulls \
            -d '{"title":"Add Helm Chart","head":"${{ input.pr_branch}}","base":"${{ input.release_branch}}","body":"This PR adds the Helm Chart to the uat branch."}'
