name: matrix-input-loop

on:
  workflow_dispatch:
    inputs:
      repo_names:
        description: 'Comma-separated repo names (e.g. repo1,repo2)'
        required: true
        type: string
      release_branches:
        description: 'Comma-separated release branches (e.g. uat,uat)'
        required: true
        type: string
      pr_branches:
        description: 'Comma-separated PR branches (e.g. feature-branch-1,feature-branch-2)'
        required: true
        type: string
      product_names:
        description: 'Comma-separated product names (e.g. productA,productB)'
        required: true
        type: string

jobs:
  Enable_Helm_Chart_Scan:
    runs-on: medium-runner
    steps:
      - name: Checkout main repo
        uses: actions/checkout@v4

      - name: Split and process each set
        env:
          REPO_NAMES: ${{ github.event.inputs.repo_names }}
          RELEASE_BRANCHES: ${{ github.event.inputs.release_branches }}
          PR_BRANCHES: ${{ github.event.inputs.pr_branches }}
          PRODUCT_NAMES: ${{ github.event.inputs.product_names }}
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
        run: |
          for i in "${!repos[@]}"; do
            repo=$(echo "${repos[$i]}" | xargs)
            release=$(echo "${releases[$i]}" | xargs)
            pr=$(echo "${prs[$i]}" | xargs)
            product=$(echo "${products[$i]}" | xargs)
            echo "Processing: repo=$repo, release=$release, pr=$pr, product=$product"
            git clone --branch "$release" "https://x-access-token:${GITHUB_TOKEN}@github.com/m2pfintech/$repo.git" "$repo"
            cd "$repo"
            git checkout -b "$pr"
            mkdir -p .github/workflows
            echo '' >> .github/workflows/ci.yml
            cat ${GITHUB_WORKSPACE}/Helm-Chart >> .github/workflows/ci.yml
            sed -i '/secrets: inherit/a\    with:\n      product_name: '"$product" .github/workflows/ci.yml
            git config --global user.name "DevSecOps"
            git config --global user.email "devsecops@gmail.com"
            git add .github/workflows/ci.yml
            git commit -m "Helm Chart Scan"
            git push --set-upstream origin "$pr"
            cd ..
          done
